# Web scraping configuration
scraping:
  batch_size: 100
  max_retries: 3
  timeout: 30
  headers:
    User-Agent: "LLM7 Scraper/0.1.0"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9"
    Accept-Language: "en-US,en;q=0.5"
  rate_limit: 1
  async_enabled: true

# Vector database and document storage configuration
memory:
  database_path: "storage/chroma_db"
  collection_name: "documents"
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  dimension: 768
  distance_metric: "cosine"
  chunking:
    enabled: true
    chunk_size: 512
    overlap: 50

# LLM configuration (Ollama)
llm:
  model_name: "llama2"
  base_url: "http://localhost:11434"
  temperature: 0.7
  max_tokens: 2000
  retry_count: 3
  timeout: 60
  stream_enabled: true
  system_prompt: "You are a helpful AI assistant focused on accurate information."

# Logging configuration
logging:
  level: "INFO"
  file_path: "logs/llm7.log"
  max_size: 10485760
  backup_count: 5

# Storage configuration
storage:
  temp_dir: "storage/temp"
  cache_dir: "storage/cache"
  max_cache_size: 1073741824
