# Application Settings
app_name: LLM7
version: "0.1.0"

# Web scraping configuration
scraping:
  batch_size: 100
  max_retries: 3
  timeout: 30
  headers:
    User-Agent: "LLM7 Scraper/0.1.0"
    Accept: "text/html,application/xhtml+xml,application/xml;q=0.9"
    Accept-Language: "en-US,en;q=0.5"
  rate_limit: 1
  async_enabled: true

# Vector database and document storage configuration
memory:
  database_path: "storage/chroma_db"
  collection_name: "documents"
  embedding_model: "sentence-transformers/all-mpnet-base-v2"
  dimension: 768
  distance_metric: "cosine"
  chunking:
    enabled: true
    chunk_size: 512
    overlap: 50

# LLM configuration (Ollama)
llm:
  default_model: mistral  # specify which model to use by default
  
  # Default parameters that apply to all models unless overridden
  defaults:
    temperature: 0.7
    max_tokens: 2000
    context_window: 4096
    top_p: 0.9
    top_k: 40
    repeat_penalty: 1.1
    
  # Model-specific configurations (override defaults)
  models:
    mistral:
      system_prompt: "You are a helpful AI assistant."
      # Any parameter not specified here will use the defaults
      
    codellama:
      temperature: 0.5
      system_prompt: "You are an expert coding assistant."
      repeat_penalty: 1.2
      
    llama2:
      temperature: 0.8
      system_prompt: "You are a helpful AI assistant."
      
    neural-chat:
      # Uses all defaults, just needs a different prompt
      system_prompt: "You are a conversational AI assistant."
      
    dolphin-phi:
      context_window: 2048
      temperature: 0.6
      system_prompt: "You are a helpful AI assistant."
      
  # Advanced configuration options
  options:
    enable_function_calling: true
    stream_response: false
    timeout: 30  # seconds
    max_retries: 3
    
  # Add any model by following the same pattern
  # modelname:
  #   parameter: value

# Logging configuration
logging:
  level: "INFO"
  file_path: "logs/llm7.log"
  max_size: 10485760
  backup_count: 5

# Storage configuration
storage:
  temp_dir: "storage/temp"
  cache_dir: "storage/cache"
  max_cache_size: 1073741824
